apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-python-app
  template:
    metadata:
      labels:
        app: otel-python-app
    spec:
      containers:
      - name: otel-python-app
        image: yourdockerhubusername/otel-python-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.monitoring.svc.cluster.local:4317"
