apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: otel-col
  endpoints:
  - port: prometheus
    path: /metrics
    interval: 15s
